// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF6DTchXULQmLWNRsOnEgdFLEhbaGjAGQ',
    appId: '1:116599084408:web:d014c4386eb0c8bc63248d',
    messagingSenderId: '116599084408',
    projectId: 'intelvt',
    authDomain: 'intelvt.firebaseapp.com',
    storageBucket: 'intelvt.firebasestorage.app',
    measurementId: 'G-PG2PE3K7S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5_GMa2fP_Hmo00DsQ1myJ0OQ3L6dPONg',
    appId: '1:1096463697014:android:dc5ef3f32a1607bb978b57',
    messagingSenderId: '1096463697014',
    projectId: 'intelvt-mobile-first',
    storageBucket: 'intelvt-mobile-first.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmkoVgYmTQO8Yl9nAk9G6TFUzqc9l8dOA',
    appId: '1:1096463697014:ios:1df37b63a5f5ec71978b57',
    messagingSenderId: '1096463697014',
    projectId: 'intelvt-mobile-first',
    storageBucket: 'intelvt-mobile-first.firebasestorage.app',
    iosBundleId: 'com.example.intelvtMobileFirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnJWGpgULjZeyTXje5-2rPkCkLH4ot4Ew',
    appId: '1:116599084408:ios:1aa1961ec976f20f63248d',
    messagingSenderId: '116599084408',
    projectId: 'intelvt',
    storageBucket: 'intelvt.firebasestorage.app',
    iosBundleId: 'com.example.intelvtMobileFirst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF6DTchXULQmLWNRsOnEgdFLEhbaGjAGQ',
    appId: '1:116599084408:web:7cbf86103bc75ce563248d',
    messagingSenderId: '116599084408',
    projectId: 'intelvt',
    authDomain: 'intelvt.firebaseapp.com',
    storageBucket: 'intelvt.firebasestorage.app',
    measurementId: 'G-0ZZR4KW5SL',
  );
}