// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfZ-Dxvp7VJSzIj4O7s-qXAW8MKdG0cDE',
    appId: '1:1020920479762:web:5b7e8e232961a4efabd8cb',
    messagingSenderId: '1020920479762',
    projectId: 'intelvtmain',
    authDomain: 'intelvtmain.firebaseapp.com',
    storageBucket: 'intelvtmain.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2kJ7y4aWl-42imvelx70bXZ3B72nuZdE',
    appId: '1:1020920479762:android:ef7d1c5df686a327abd8cb',
    messagingSenderId: '1020920479762',
    projectId: 'intelvtmain',
    storageBucket: 'intelvtmain.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU1lZ8Q4pGpdMmzByJPf-9CLPi9rDjBHs',
    appId: '1:1020920479762:ios:c0363a40c41bfadcabd8cb',
    messagingSenderId: '1020920479762',
    projectId: 'intelvtmain',
    storageBucket: 'intelvtmain.firebasestorage.app',
    iosBundleId: 'intelvt.iphone',
  );

}